version: "3.3"

services:
  mongodb:
    image: mongo:4.0.24
    ports:
      - "27017:27017"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    depends_on:
      - mongodb
  backend:
    image: node:14.15.5-alpine3.13
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "5000:5000"
    depends_on:
      - elastic
    volumes:
      - ./backendqanda:/app
  frontend:
    image: node:14.15.5-alpine3.13
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontendqanda:/app
